name: helloworld

on: push

jobs:
  linux-build:
    name: ubuntu-build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repositories
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup build environment
        run: |-
          sudo apt-get update
          sudo apt-get install -y gcc

      - name: Build
        run: |-
          gcc helloworld.c -o helloworld
          chmod a+x helloworld

      - uses: actions/upload-artifact@v4
        with:
          name: helloworld_${{ github.sha }}
          retention-days: 14
          path: |-
              helloworld

  linux-test:
    needs: ['linux-build']
    name: linux-test
    continue-on-error: true
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: helloworld_${{ github.sha }}

      - name: Run
        run: |-
          ./helloworld